### ISSUE TITLE
error when use python3 crawler_main.py -g 106955  -e 求租  -v

### ISSUE THREAD

**Issue by buzai** [lesywix/douban_group_spy#1]
File "crawler_main.py", line 45
    lg.info(f'[post] update existing post: {post.post_id}')
                                                         ^
SyntaxError: invalid syntax

**Comment by lesywix** [comment]
What Python version did you use？The script should use py3

**Comment by buzai** [comment]
@weixianglin
Python 3.5.2 (default, Nov 12 2018, 13:43:14)

**Comment by lesywix** [comment]
I found the problem. You should try python version >= 3.6. Because the code use f-string which introduced by Python 3.6.
