### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by secsilm** [lesywix/douban_group_spy#16]
未登录情况下，豆瓣小组只能爬取到 `start=250`，再往后就需要登录了。

我看您的代码中没有登陆相关代码，请问您是如何解决这个登录问题，以及频繁更换IP登录会造成账号异常的问题的？谢谢！

**Comment by lesywix** [comment]
看得到具体的报错信息吗？

**Comment by lesywix** [comment]
添加了 Cookie #18
