### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_text‘

### ISSUE THREAD

**Issue by Raychanan** [lesywix/douban_group_spy#17]
非常感谢开发这个包！

根据建议逐步执行命令，但执行`python crawler_main.py -g 106955 -g baoanzufang -k 灵芝 -k 翻身 -e 求租`时遇到下列错误。请问如何解决呢？谢谢！

![image](https://user-images.githubusercontent.com/53246211/149452018-fe9f1f2a-06e4-4d61-9155-d877c4eafc6a.png)

**Comment by icerchou** [comment]
我也遇到这个问题了 同问

**Comment by lesywix** [comment]
Fixed on #18
